[package]
edition = "2021"
exclude = ["index.node"]
license = "GPL-3.0"
name = "desktop_native"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[features]
default = []
manual_test = []

[dependencies]
aes = "=0.8.2"
anyhow = "=1.0.71"
base64 = "=0.21.2"
cbc = { version = "=0.1.2", features = ["alloc"] }
napi = { version = "=2.13.1", features = ["async"] }
napi-derive = "=2.13.0"
rand = "=0.8.5"
retry = "=2.0.0"
scopeguard = "=1.1.0"
sha2 = "=0.10.6"
thiserror = "=1.0.40"
tokio = { version = "=1.28.2", features = ["full"] }
typenum = "=1.16.0"

[build-dependencies]
napi-build = "=2.0.1"

[target.'cfg(windows)'.dependencies]
widestring = "=0.5.1"
windows = { version = "=0.48.0", features = [
  "Foundation",
  "Security_Credentials_UI",
  "Security_Cryptography",
  "Storage_Streams",
  "Win32_Foundation",
  "Win32_Security_Credentials",
  "Win32_System_ProcessStatus",
  "Win32_System_Threading",
  "Win32_System_WinRT",
  "Win32_UI_Input_KeyboardAndMouse",
  "Win32_UI_TextServices",
  "Win32_UI_WindowsAndMessaging",
] }

[target.'cfg(windows)'.dev-dependencies]
keytar = "=0.1.6"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "=0.9.3"
security-framework = "=2.9.1"
security-framework-sys = "=2.9.0"

[target.'cfg(target_os = "linux")'.dependencies]
gio = "=0.17.9"
libsecret = "=0.3.0"
